"""empty message

Revision ID: 0b71e617a3aa
Revises: e8b2504e3df0
Create Date: 2024-05-27 13:39:16.057877

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0b71e617a3aa'
down_revision = 'e8b2504e3df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
