"""empty message

Revision ID: f175cf7797f4
Revises: ef96bb7886b7
Create Date: 2024-06-20 16:46:23.206740

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f175cf7797f4'
down_revision = 'ef96bb7886b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('energy', sa.Integer(), server_default="500", default=lambda :500, nullable=False))
    op.add_column('user', sa.Column('last_energy_change', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('max_energy', sa.Integer(), server_default="500", default=lambda :500, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'max_energy')
    op.drop_column('user', 'last_energy_change')
    op.drop_column('user', 'energy')
    # ### end Alembic commands ###
